"""initial schema

Revision ID: 044ddddbee2d
Revises: 
Create Date: 2026-09-15 03:51:04.897507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '044ddddbee2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('auth_kind', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('client_ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_path'), 'audit_log', ['path'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('dependencies',
    sa.Column('previous_id', sa.BigInteger(), nullable=False),
    sa.Column('previous_type', sa.String(), nullable=False),
    sa.Column('next_id', sa.BigInteger(), nullable=False),
    sa.Column('next_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('previous_id', 'previous_type', 'next_id', 'next_type')
    )
    op.create_index(op.f('ix_dependencies_next_id'), 'dependencies', ['next_id'], unique=False)
    op.create_index(op.f('ix_dependencies_previous_id'), 'dependencies', ['previous_id'], unique=False)
    op.create_table('execution_workers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('tasks_failed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_workers_hostname'), 'execution_workers', ['hostname'], unique=False)
    op.create_index(op.f('ix_execution_workers_last_heartbeat'), 'execution_workers', ['last_heartbeat'], unique=False)
    op.create_index(op.f('ix_execution_workers_status'), 'execution_workers', ['status'], unique=False)
    op.create_table('registered_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entrypoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_kwargs', sa.JSON(), nullable=True),
    sa.Column('preservation_mode', sa.String(), nullable=True),
    sa.Column('runner_mode', sa.String(), server_default='subprocess', nullable=False),
    sa.Column('dockerfile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('git_remote', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kubernetes_config', sa.JSON(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_registered_jobs_name'), 'registered_jobs', ['name'], unique=False)
    op.create_index(op.f('ix_registered_jobs_next_run_at'), 'registered_jobs', ['next_run_at'], unique=False)
    op.create_table('table_context_refs',
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('context_id', sa.BigInteger(), nullable=False),
    sa.Column('advisory_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('table_name', 'context_id')
    )
    op.create_table('table_pin_refs',
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('table_name', 'task_id')
    )
    op.create_table('table_registry',
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('schema_doc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('table_name')
    )
    op.create_index(op.f('ix_table_registry_created_at'), 'table_registry', ['created_at'], unique=False)
    op.create_index(op.f('ix_table_registry_job_id'), 'table_registry', ['job_id'], unique=False)
    op.create_table('table_run_refs',
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('table_name', 'run_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.String(), server_default='viewer', nullable=False),
    sa.Column('disabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('viewer_dashboards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('queries', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_viewer_dashboards_name'), 'viewer_dashboards', ['name'], unique=False)
    op.create_table('viewer_queries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('where', sa.Text(), nullable=True),
    sa.Column('fields', sa.Text(), nullable=True),
    sa.Column('order_by', sa.Text(), nullable=True),
    sa.Column('cell_view', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_viewer_queries_name'), 'viewer_queries', ['name'], unique=False)
    op.create_index(op.f('ix_viewer_queries_object'), 'viewer_queries', ['object'], unique=False)
    op.create_index(op.f('ix_viewer_queries_scope'), 'viewer_queries', ['scope'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('registered_job_id', sa.BigInteger(), nullable=True),
    sa.Column('preservation_mode', sa.String(), server_default='NONE', nullable=False),
    sa.Column('runner_mode', sa.String(), server_default='subprocess', nullable=False),
    sa.Column('runner', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['registered_job_id'], ['registered_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_name'), 'jobs', ['name'], unique=False)
    op.create_index(op.f('ix_jobs_registered_job_id'), 'jobs', ['registered_job_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_group_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['parent_group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_job_id'), 'groups', ['job_id'], unique=False)
    op.create_index(op.f('ix_groups_parent_group_id'), 'groups', ['parent_group_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('entrypoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kwargs', sa.JSON(), nullable=True),
    sa.Column('entry_type', sa.String(), nullable=True),
    sa.Column('command', sa.JSON(), nullable=True),
    sa.Column('command_env', sa.JSON(), nullable=True),
    sa.Column('image_source', sa.JSON(), nullable=True),
    sa.Column('is_image_build', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_worker_id', sa.BigInteger(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('retry_after', sa.DateTime(), nullable=True),
    sa.Column('run_ids', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('run_statuses', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('run_epoch', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['execution_worker_id'], ['execution_workers.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_execution_worker_id'), 'tasks', ['execution_worker_id'], unique=False)
    op.create_index(op.f('ix_tasks_group_id'), 'tasks', ['group_id'], unique=False)
    op.create_index(op.f('ix_tasks_job_id'), 'tasks', ['job_id'], unique=False)
    op.create_index('ix_tasks_job_id_status', 'tasks', ['job_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('remote_task_results',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('run_epoch', sa.BigInteger(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('result_ref', sa.JSON(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'run_epoch')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remote_task_results')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index('ix_tasks_job_id_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_job_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_group_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_execution_worker_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_groups_parent_group_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_job_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_registered_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_name'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_viewer_queries_scope'), table_name='viewer_queries')
    op.drop_index(op.f('ix_viewer_queries_object'), table_name='viewer_queries')
    op.drop_index(op.f('ix_viewer_queries_name'), table_name='viewer_queries')
    op.drop_table('viewer_queries')
    op.drop_index(op.f('ix_viewer_dashboards_name'), table_name='viewer_dashboards')
    op.drop_table('viewer_dashboards')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('table_run_refs')
    op.drop_index(op.f('ix_table_registry_job_id'), table_name='table_registry')
    op.drop_index(op.f('ix_table_registry_created_at'), table_name='table_registry')
    op.drop_table('table_registry')
    op.drop_table('table_pin_refs')
    op.drop_table('table_context_refs')
    op.drop_index(op.f('ix_registered_jobs_next_run_at'), table_name='registered_jobs')
    op.drop_index(op.f('ix_registered_jobs_name'), table_name='registered_jobs')
    op.drop_table('registered_jobs')
    op.drop_index(op.f('ix_execution_workers_status'), table_name='execution_workers')
    op.drop_index(op.f('ix_execution_workers_last_heartbeat'), table_name='execution_workers')
    op.drop_index(op.f('ix_execution_workers_hostname'), table_name='execution_workers')
    op.drop_table('execution_workers')
    op.drop_index(op.f('ix_dependencies_previous_id'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_next_id'), table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_path'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
