"""add sandbox_files

Revision ID: 12875c98f9ce
Revises: 4c31f07aa3ea
Create Date: 2026-10-09 19:15:51.126884

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12875c98f9ce"
down_revision: str | Sequence[str] | None = "4c31f07aa3ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sandbox_files",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("git_remote", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("git_sha", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_names", sa.JSON(), nullable=False),
        sa.Column("job_ids", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("submitted_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_index(op.f("ix_sandbox_files_status"), "sandbox_files", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sandbox_files_status"), table_name="sandbox_files")
    op.drop_table("sandbox_files")
    # ### end Alembic commands ###
