"""add fail_fast flag to registered_jobs and jobs

Revision ID: 128f65608205
Revises: 3e70da4a33c9
Create Date: 2026-06-06 05:54:55.185580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '128f65608205'
down_revision: Union[str, Sequence[str], None] = '3e70da4a33c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('fail_fast', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('registered_jobs', sa.Column('fail_fast', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registered_jobs', 'fail_fast')
    op.drop_column('jobs', 'fail_fast')
    # ### end Alembic commands ###
