"""add table_registry tenant_id

Revision ID: 1da307dfbd95
Revises: 39cd0baa9f90
Create Date: 2026-08-24 03:24:56.828943

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1da307dfbd95"
down_revision: str | Sequence[str] | None = "39cd0baa9f90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("table_registry", sa.Column("tenant_id", sa.BigInteger(), server_default="1", nullable=False))
    op.create_index(op.f("ix_table_registry_tenant_id"), "table_registry", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_table_registry_tenant_id"), table_name="table_registry")
    op.drop_column("table_registry", "tenant_id")
    # ### end Alembic commands ###
