"""tenant rbac: tenants, memberships, tenant_id, superadmin

Revision ID: 39cd0baa9f90
Revises: 42ce3a909fbf
Create Date: 2026-08-21 17:26:22.315196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '39cd0baa9f90'
down_revision: Union[str, Sequence[str], None] = '42ce3a909fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('tenant_memberships',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id')
    )
    op.create_index(op.f('ix_tenant_memberships_tenant_id'), 'tenant_memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_user_id'), 'tenant_memberships', ['user_id'], unique=False)
    op.add_column('jobs', sa.Column('tenant_id', sa.BigInteger(), server_default='1', nullable=False))
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.add_column('registered_jobs', sa.Column('tenant_id', sa.BigInteger(), server_default='1', nullable=False))
    op.drop_constraint(op.f('registered_jobs_name_key'), 'registered_jobs', type_='unique')
    op.create_index(op.f('ix_registered_jobs_tenant_id'), 'registered_jobs', ['tenant_id'], unique=False)
    op.create_unique_constraint(None, 'registered_jobs', ['tenant_id', 'name'])
    op.add_column('users', sa.Column('superadmin', sa.Boolean(), server_default='0', nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'superadmin')
    op.drop_constraint(None, 'registered_jobs', type_='unique')
    op.drop_index(op.f('ix_registered_jobs_tenant_id'), table_name='registered_jobs')
    op.create_unique_constraint(op.f('registered_jobs_name_key'), 'registered_jobs', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('registered_jobs', 'tenant_id')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_column('jobs', 'tenant_id')
    op.drop_index(op.f('ix_tenant_memberships_user_id'), table_name='tenant_memberships')
    op.drop_index(op.f('ix_tenant_memberships_tenant_id'), table_name='tenant_memberships')
    op.drop_table('tenant_memberships')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
