"""tenant rbac: tenants, memberships, tenant_id, superadmin

Revision ID: 39cd0baa9f90
Revises: 42ce3a909fbf
Create Date: 2026-08-21 17:26:22.315196

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39cd0baa9f90"
down_revision: str | Sequence[str] | None = "42ce3a909fbf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    # Seed the default tenant (fixed id 1) — existing rows backfill to it via
    # the tenant_id server_default below.
    op.execute("INSERT INTO tenants (id, slug, name, created_at) VALUES (1, 'default', 'Default', CURRENT_TIMESTAMP)")
    op.create_table(
        "tenant_memberships",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "user_id"),
    )
    op.create_index(op.f("ix_tenant_memberships_tenant_id"), "tenant_memberships", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_tenant_memberships_user_id"), "tenant_memberships", ["user_id"], unique=False)
    op.add_column("jobs", sa.Column("tenant_id", sa.BigInteger(), server_default="1", nullable=False))
    op.create_index(op.f("ix_jobs_tenant_id"), "jobs", ["tenant_id"], unique=False)
    op.add_column("registered_jobs", sa.Column("tenant_id", sa.BigInteger(), server_default="1", nullable=False))
    op.drop_constraint(op.f("registered_jobs_name_key"), "registered_jobs", type_="unique")
    op.create_index(op.f("ix_registered_jobs_tenant_id"), "registered_jobs", ["tenant_id"], unique=False)
    op.create_unique_constraint(None, "registered_jobs", ["tenant_id", "name"])
    op.add_column("users", sa.Column("superadmin", sa.Boolean(), server_default="0", nullable=False))
    # Existing global admins become superadmins; viewers keep read access via a
    # default-tenant viewer membership (reusing the user id as the membership
    # PK is safe — snowflakes are globally unique).
    op.execute("UPDATE users SET superadmin = (role = 'admin')")
    op.execute(
        "INSERT INTO tenant_memberships (id, tenant_id, user_id, role, created_at) "
        "SELECT id, 1, id, 'viewer', CURRENT_TIMESTAMP FROM users WHERE role = 'viewer'"
    )
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("role", sa.VARCHAR(), server_default="viewer", autoincrement=False, nullable=False)
    )
    op.execute("UPDATE users SET role = CASE WHEN superadmin THEN 'admin' ELSE 'viewer' END")
    op.drop_column("users", "superadmin")
    op.drop_constraint(None, "registered_jobs", type_="unique")
    op.drop_index(op.f("ix_registered_jobs_tenant_id"), table_name="registered_jobs")
    op.create_unique_constraint(
        op.f("registered_jobs_name_key"), "registered_jobs", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("registered_jobs", "tenant_id")
    op.drop_index(op.f("ix_jobs_tenant_id"), table_name="jobs")
    op.drop_column("jobs", "tenant_id")
    op.drop_index(op.f("ix_tenant_memberships_user_id"), table_name="tenant_memberships")
    op.drop_index(op.f("ix_tenant_memberships_tenant_id"), table_name="tenant_memberships")
    op.drop_table("tenant_memberships")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###
