"""add tasks.is_image_build

Revision ID: 42ce3a909fbf
Revises: 79f037d1198d
Create Date: 2026-08-01 04:27:25.737551

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42ce3a909fbf"
down_revision: str | Sequence[str] | None = "79f037d1198d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("is_image_build", sa.Boolean(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "is_image_build")
    # ### end Alembic commands ###
