"""runner on worker

Revision ID: 4c31f07aa3ea
Revises: d862d9d1e8ae
Create Date: 2026-10-07 18:21:57.404040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c31f07aa3ea'
down_revision: Union[str, Sequence[str], None] = 'd862d9d1e8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('resources', sa.JSON(), nullable=True))
    op.drop_column('jobs', 'runner')
    op.drop_column('jobs', 'runner_mode')
    op.add_column('registered_jobs', sa.Column('build', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('registered_jobs', sa.Column('resources', sa.JSON(), nullable=True))
    op.drop_column('registered_jobs', 'kubernetes_config')
    op.drop_column('registered_jobs', 'runner_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registered_jobs', sa.Column('runner_mode', sa.VARCHAR(), server_default=sa.text("'subprocess'::character varying"), autoincrement=False, nullable=False))
    op.add_column('registered_jobs', sa.Column('kubernetes_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('registered_jobs', 'resources')
    op.drop_column('registered_jobs', 'build')
    op.add_column('jobs', sa.Column('runner_mode', sa.VARCHAR(), server_default=sa.text("'subprocess'::character varying"), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('runner', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'resources')
    # ### end Alembic commands ###
