"""add api_tokens.tenant_id

Revision ID: 5733d48079d5
Revises: ff9242208cc6
Create Date: 2026-09-12 20:12:55.343163

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5733d48079d5"
down_revision: str | Sequence[str] | None = "ff9242208cc6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_tokens", sa.Column("tenant_id", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_api_tokens_tenant_id"), "api_tokens", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_tokens_tenant_id"), table_name="api_tokens")
    op.drop_column("api_tokens", "tenant_id")
    # ### end Alembic commands ###
