"""add UPSTREAM_FAILED to tasks.status CHECK constraint

Revision ID: 5d244433f837
Revises: c5c36f1524db
Create Date: 2026-05-11 17:39:33.230707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d244433f837'
down_revision: Union[str, Sequence[str], None] = 'c5c36f1524db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
