"""per task image source

Revision ID: 79f037d1198d
Revises: b2e9d5a13603
Create Date: 2026-07-31 14:27:42.915635

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "79f037d1198d"
down_revision: str | Sequence[str] | None = "b2e9d5a13603"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted: the tasks.build_task_id
    # column (whose FK autogenerate could not see; it is filtered in env.py)
    # must be dropped before build_tasks, or Postgres refuses the DROP TABLE ###
    op.add_column("tasks", sa.Column("image_source", sa.JSON(), nullable=True))
    op.drop_index(op.f("ix_tasks_build_task_id"), table_name="tasks")
    op.drop_column("tasks", "build_task_id")
    op.drop_index(op.f("ix_build_tasks_image_key"), table_name="build_tasks")
    op.drop_index(op.f("ix_build_tasks_status"), table_name="build_tasks")
    op.drop_table("build_tasks")
    op.add_column("registered_jobs", sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column("registered_jobs", "runner")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted to mirror the upgrade
    # ordering and restore the FK autogenerate could not see ###
    op.add_column(
        "registered_jobs",
        sa.Column("runner", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    op.drop_column("registered_jobs", "image")
    op.create_table(
        "build_tasks",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("image_key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("image_tag", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("git_remote", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("git_sha", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("dockerfile", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("holder_execution_worker_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("lease_expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("log_path", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("attempts", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("max_retries", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("started_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("finished_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("build_tasks_pkey")),
        sa.UniqueConstraint(
            "image_key",
            name=op.f("build_tasks_image_key_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_build_tasks_status"), "build_tasks", ["status"], unique=False)
    op.create_index(op.f("ix_build_tasks_image_key"), "build_tasks", ["image_key"], unique=False)
    op.add_column("tasks", sa.Column("build_task_id", sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_index(op.f("ix_tasks_build_task_id"), "tasks", ["build_task_id"], unique=False)
    op.create_foreign_key(op.f("tasks_build_task_id_fkey"), "tasks", "build_tasks", ["build_task_id"], ["id"])
    op.drop_column("tasks", "image_source")
    # ### end Alembic commands ###
