"""drop oidc_subject and oidc_states

Revision ID: a2dc0ee28a04
Revises: 5733d48079d5
Create Date: 2026-09-13 08:03:08.210653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2dc0ee28a04'
down_revision: Union[str, Sequence[str], None] = '5733d48079d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oidc_states_token_hash'), table_name='oidc_states')
    op.drop_table('oidc_states')
    op.drop_index(op.f('ix_users_oidc_subject'), table_name='users')
    op.drop_column('users', 'oidc_subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oidc_subject', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_oidc_subject'), 'users', ['oidc_subject'], unique=True)
    op.create_table('oidc_states',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nonce', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code_verifier', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('consumed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('oidc_states_pkey'))
    )
    op.create_index(op.f('ix_oidc_states_token_hash'), 'oidc_states', ['token_hash'], unique=True)
    # ### end Alembic commands ###
