"""add composite index ix_tasks_job_id_status

Revision ID: b72b3d09a353
Revises: 5d244433f837
Create Date: 2026-05-12 04:22:15.004407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b72b3d09a353'
down_revision: Union[str, Sequence[str], None] = '5d244433f837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tasks_job_id_status', 'tasks', ['job_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_job_id_status', table_name='tasks')
    # ### end Alembic commands ###
