"""add table_registry name column with unique tenant name

Revision ID: c58aa62bafc1
Revises: 1da307dfbd95
Create Date: 2026-09-04 16:25:00.596618

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c58aa62bafc1"
down_revision: str | Sequence[str] | None = "1da307dfbd95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("table_registry", sa.Column("name", sa.String(), nullable=True))
    op.create_unique_constraint(None, "table_registry", ["tenant_id", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "table_registry", type_="unique")
    op.drop_column("table_registry", "name")
    # ### end Alembic commands ###
