"""add table_registry name column with unique tenant name

Revision ID: c58aa62bafc1
Revises: 1da307dfbd95
Create Date: 2026-09-04 16:25:00.596618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c58aa62bafc1'
down_revision: Union[str, Sequence[str], None] = '1da307dfbd95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_registry', sa.Column('name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'table_registry', ['tenant_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table_registry', type_='unique')
    op.drop_column('table_registry', 'name')
    # ### end Alembic commands ###
