"""add table_registry tenant_id

Revision ID: d4943bf13e4a
Revises: 39cd0baa9f90
Create Date: 2026-08-24 03:17:36.997444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd4943bf13e4a'
down_revision: Union[str, Sequence[str], None] = '39cd0baa9f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_context_refs', sa.Column('tenant_id', sa.BigInteger(), server_default='1', nullable=False))
    op.create_index(op.f('ix_table_context_refs_tenant_id'), 'table_context_refs', ['tenant_id'], unique=False)
    op.add_column('table_pin_refs', sa.Column('tenant_id', sa.BigInteger(), server_default='1', nullable=False))
    op.create_index(op.f('ix_table_pin_refs_tenant_id'), 'table_pin_refs', ['tenant_id'], unique=False)
    op.add_column('table_registry', sa.Column('tenant_id', sa.BigInteger(), server_default='1', nullable=False))
    op.create_index(op.f('ix_table_registry_tenant_id'), 'table_registry', ['tenant_id'], unique=False)
    op.add_column('table_run_refs', sa.Column('tenant_id', sa.BigInteger(), server_default='1', nullable=False))
    op.create_index(op.f('ix_table_run_refs_tenant_id'), 'table_run_refs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_run_refs_tenant_id'), table_name='table_run_refs')
    op.drop_column('table_run_refs', 'tenant_id')
    op.drop_index(op.f('ix_table_registry_tenant_id'), table_name='table_registry')
    op.drop_column('table_registry', 'tenant_id')
    op.drop_index(op.f('ix_table_pin_refs_tenant_id'), table_name='table_pin_refs')
    op.drop_column('table_pin_refs', 'tenant_id')
    op.drop_index(op.f('ix_table_context_refs_tenant_id'), table_name='table_context_refs')
    op.drop_column('table_context_refs', 'tenant_id')
    # ### end Alembic commands ###
