"""move default tenant id server_default to 1 shl 62

Revision ID: d6723953a1bb
Revises: 1da307dfbd95
Create Date: 2026-09-05 11:41:34.213484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd6723953a1bb'
down_revision: Union[str, Sequence[str], None] = '1da307dfbd95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'tenant_id',
               existing_type=sa.BIGINT(),
               server_default='4611686018427387904',
               existing_nullable=False)
    op.alter_column('registered_jobs', 'tenant_id',
               existing_type=sa.BIGINT(),
               server_default='4611686018427387904',
               existing_nullable=False)
    op.alter_column('table_registry', 'tenant_id',
               existing_type=sa.BIGINT(),
               server_default='4611686018427387904',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('table_registry', 'tenant_id',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'1'::bigint"),
               existing_nullable=False)
    op.alter_column('registered_jobs', 'tenant_id',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'1'::bigint"),
               existing_nullable=False)
    op.alter_column('jobs', 'tenant_id',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'1'::bigint"),
               existing_nullable=False)
    # ### end Alembic commands ###
