"""add users.totp_last_step

Revision ID: d862d9d1e8ae
Revises: 044ddddbee2d
Create Date: 2026-09-27 16:47:03.583044

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d862d9d1e8ae"
down_revision: str | Sequence[str] | None = "044ddddbee2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("totp_last_step", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "totp_last_step")
    # ### end Alembic commands ###
