"""add viewer_queries and viewer_dashboards

Revision ID: dbb17fe55626
Revises: d6723953a1bb
Create Date: 2026-09-11 01:46:31.505135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dbb17fe55626'
down_revision: Union[str, Sequence[str], None] = 'd6723953a1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewer_dashboards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), server_default='4611686018427387904', nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('queries', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name')
    )
    op.create_index(op.f('ix_viewer_dashboards_name'), 'viewer_dashboards', ['name'], unique=False)
    op.create_index(op.f('ix_viewer_dashboards_tenant_id'), 'viewer_dashboards', ['tenant_id'], unique=False)
    op.create_table('viewer_queries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), server_default='4611686018427387904', nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('where', sa.Text(), nullable=True),
    sa.Column('fields', sa.Text(), nullable=True),
    sa.Column('order_by', sa.Text(), nullable=True),
    sa.Column('cell_view', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name')
    )
    op.create_index(op.f('ix_viewer_queries_name'), 'viewer_queries', ['name'], unique=False)
    op.create_index(op.f('ix_viewer_queries_object'), 'viewer_queries', ['object'], unique=False)
    op.create_index(op.f('ix_viewer_queries_scope'), 'viewer_queries', ['scope'], unique=False)
    op.create_index(op.f('ix_viewer_queries_tenant_id'), 'viewer_queries', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_viewer_queries_tenant_id'), table_name='viewer_queries')
    op.drop_index(op.f('ix_viewer_queries_scope'), table_name='viewer_queries')
    op.drop_index(op.f('ix_viewer_queries_object'), table_name='viewer_queries')
    op.drop_index(op.f('ix_viewer_queries_name'), table_name='viewer_queries')
    op.drop_table('viewer_queries')
    op.drop_index(op.f('ix_viewer_dashboards_tenant_id'), table_name='viewer_dashboards')
    op.drop_index(op.f('ix_viewer_dashboards_name'), table_name='viewer_dashboards')
    op.drop_table('viewer_dashboards')
    # ### end Alembic commands ###
