/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v0/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v0_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v0_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v0_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change Password
         * @description Any role may change their own password — ``/users`` is admin-only.
         */
        put: operations["change_password_api_v0_auth_me_password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v0_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream change signals
         * @description `text/event-stream` of `changed` events; refetch after each one. Sends a keepalive comment while idle.
         */
        get: operations["stream_events_api_v0_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/execution-workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Execution Workers */
        get: operations["list_execution_workers_api_v0_execution_workers_get"];
        put?: never;
        /**
         * Start Execution Worker
         * @description Spawn a detached execution worker subprocess (distributed mode only).
         *
         *     Returns ``202 Accepted`` with an empty body once the fork/exec succeeds;
         *     the caller polls ``GET /execution-workers`` to observe the new execution worker row.
         */
        post: operations["start_execution_worker_api_v0_execution_workers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/execution-workers/{execution_worker_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Execution Worker */
        post: operations["stop_execution_worker_api_v0_execution_workers__execution_worker_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v0_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/jobs/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v0_jobs__ref__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/jobs/{ref}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v0_jobs__ref__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/jobs/{ref}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Graph */
        get: operations["job_graph_api_v0_jobs__ref__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/jobs/{ref}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Stats */
        get: operations["job_stats_api_v0_jobs__ref__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/jobs:run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Job */
        post: operations["run_job_api_v0_jobs_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Objects */
        get: operations["list_objects_api_v0_objects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/objects/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Object */
        get: operations["get_object_api_v0_objects__name__get"];
        put?: never;
        post?: never;
        /** Delete Object */
        delete: operations["delete_object_api_v0_objects__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/objects:purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Purge Objects */
        post: operations["purge_objects_api_v0_objects_purge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/registered-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Registered Jobs */
        get: operations["list_registered_jobs_api_v0_registered_jobs_get"];
        put?: never;
        /** Register Job */
        post: operations["register_job_api_v0_registered_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/registered-jobs/{name}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Job */
        post: operations["disable_job_api_v0_registered_jobs__name__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/registered-jobs/{name}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable Job */
        post: operations["enable_job_api_v0_registered_jobs__name__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v0_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/tasks/{task_id}/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Task */
        post: operations["clear_task_api_v0_tasks__task_id__clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/tasks/{task_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Logs */
        get: operations["get_task_logs_api_v0_tasks__task_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tenants */
        get: operations["list_tenants_api_v0_tenants_get"];
        put?: never;
        /** Create Tenant */
        post: operations["create_tenant_api_v0_tenants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tenant */
        get: operations["get_tenant_api_v0_tenants__tenant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/tenants/{tenant_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_v0_tenants__tenant_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/tenants/{tenant_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Member */
        put: operations["set_member_api_v0_tenants__tenant_id__members__user_id__put"];
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_v0_tenants__tenant_id__members__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v0_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v0_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/users/{user_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable User */
        post: operations["disable_user_api_v0_users__user_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/users/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Password */
        put: operations["set_password_api_v0_users__user_id__password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/users/{user_id}/superadmin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Superadmin */
        put: operations["set_superadmin_api_v0_users__user_id__superadmin_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChangePasswordRequest
         * @description Self-service password change. ``current_password`` is required so a
         *     stolen access token cannot take over the account on its own.
         */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * ClearTaskView
         * @description Result of ``POST /tasks/{id}/clear`` — the reactivated job plus the
         *     full set of tasks that were reset to ``PENDING`` (target + downstream).
         */
        ClearTaskView: {
            /** Cleared Task Ids */
            cleared_task_ids?: string[];
            job: components["schemas"]["JobView"];
        };
        /**
         * ColumnInfo
         * @description Column definition including base type, nullability, array wrapping, and cardinality.
         *
         *     Attributes:
         *         type: Base ClickHouse element type (e.g., 'Int64', 'String')
         *         nullable: Whether the column allows NULL values
         *         array: Nesting depth of Array wrapping. ``0`` means plain column,
         *                ``1`` means ``Array(T)``, ``2`` means ``Array(Array(T))``, etc.
         *                Bool ``True``/``False`` are accepted as ``1``/``0`` for convenience.
         *         low_cardinality: Whether to use LowCardinality encoding
         *         fieldtype: Per-column fieldtype — scalar or array. Replaces the YAML-comment
         *                    fieldtype stored in ClickHouse today; populated from the registry's
         *                    schema_doc once Phase 3 writes it.
         */
        ColumnInfo: {
            /**
             * Array
             * @default 0
             */
            array: number;
            /** Default */
            default?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Fieldtype
             * @default s
             * @enum {string}
             */
            fieldtype: "s" | "a";
            /**
             * Low Cardinality
             * @default false
             */
            low_cardinality: boolean;
            /**
             * Nullable
             * @default false
             */
            nullable: boolean;
            /** Type */
            type: string;
        };
        /** CreateTenantRequest */
        CreateTenantRequest: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /** Password */
            password: string;
            /**
             * Superadmin
             * @default false
             */
            superadmin: boolean;
            /** Username */
            username: string;
        };
        /**
         * ExecutionWorkerView
         * @description ExecutionWorker representation used by ``GET /execution-workers``.
         */
        ExecutionWorkerView: {
            /** Hostname */
            hostname: string;
            /** Id */
            id: string;
            /**
             * Last Heartbeat
             * Format: date-time
             */
            last_heartbeat: string;
            /** Pid */
            pid: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ACTIVE" | "IDLE" | "STOPPING" | "STOPPED";
            /** Tasks Completed */
            tasks_completed: number;
            /** Tasks Failed */
            tasks_failed: number;
        };
        /**
         * GraphEdgeView
         * @description A resolved task-to-task edge.
         *
         *     ``kind`` and ``attaches_build`` are graph semantics, so they are settled
         *     here rather than re-derived per client: an image build gates every task
         *     sharing its image, and a UI that draws all of those edges buries the
         *     pipeline. ``attaches_build`` marks the one edge per root that keeps the
         *     build connected, so the rest can be collapsed.
         */
        GraphEdgeView: {
            /**
             * Attaches Build
             * @default false
             */
            attaches_build: boolean;
            /**
             * Kind
             * @default dependency
             * @enum {string}
             */
            kind: "dependency" | "build";
            /** Source Id */
            source_id: string;
            /** Target Id */
            target_id: string;
        };
        /**
         * GraphNodeView
         * @description A node in the job graph: a task, or a group container drawn around its
         *     member tasks. A group's ``status`` and timing are rolled up from every task
         *     beneath it; its ``entrypoint`` is empty and ``attempt`` is ``0``.
         */
        GraphNodeView: {
            /** Attempt */
            attempt: number;
            /** Completed At */
            completed_at?: string | null;
            /** Entrypoint */
            entrypoint: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /**
             * Is Image Build
             * @default false
             */
            is_image_build: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "task" | "group";
            /** Name */
            name: string;
            /** Parent Group Id */
            parent_group_id?: string | null;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "CLAIMED" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "PENDING_CLEANUP" | "UPSTREAM_FAILED";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobDetail
         * @description Full job representation used by ``GET /jobs/{ref}``.
         */
        JobDetail: {
            /** Completed At */
            completed_at?: string | null;
            /**
             * Completed Tasks
             * @default 0
             */
            completed_tasks: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Preservation Mode
             * @enum {string}
             */
            preservation_mode: "NONE" | "FULL";
            /** Registered Job Id */
            registered_job_id?: string | null;
            /**
             * Run Type
             * @enum {string}
             */
            run_type: "SCHEDULED" | "MANUAL";
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED";
            /** Tasks */
            tasks?: components["schemas"]["TaskView"][];
            /**
             * Total Tasks
             * @default 0
             */
            total_tasks: number;
        };
        /**
         * JobGraphView
         * @description Job dependency graph served by ``GET /jobs/{ref}/graph``.
         */
        JobGraphView: {
            /**
             * Dropped Cycle Edges
             * @default 0
             */
            dropped_cycle_edges: number;
            /** Edges */
            edges?: components["schemas"]["GraphEdgeView"][];
            /** Job Id */
            job_id: string;
            /** Nodes */
            nodes?: components["schemas"]["GraphNodeView"][];
        };
        /**
         * JobStatsView
         * @description Execution stats for a job and all its tasks.
         */
        JobStatsView: {
            /** Exec Time Ms */
            exec_time_ms?: number | null;
            /** Job Id */
            job_id: string;
            /** Job Name */
            job_name: string;
            /**
             * Job Status
             * @enum {string}
             */
            job_status: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED";
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Tasks */
            tasks?: components["schemas"]["TaskStatsView"][];
            /** Total Tasks */
            total_tasks: number;
            /** Wall Time Ms */
            wall_time_ms?: number | null;
        };
        /**
         * JobView
         * @description Compact job representation used by list endpoints.
         */
        JobView: {
            /** Completed At */
            completed_at?: string | null;
            /**
             * Completed Tasks
             * @default 0
             */
            completed_tasks: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Preservation Mode
             * @enum {string}
             */
            preservation_mode: "NONE" | "FULL";
            /** Registered Job Id */
            registered_job_id?: string | null;
            /**
             * Run Type
             * @enum {string}
             */
            run_type: "SCHEDULED" | "MANUAL";
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED";
            /**
             * Total Tasks
             * @default 0
             */
            total_tasks: number;
        };
        /**
         * LogLine
         * @description One captured output line tagged with its stream, level, and emit time.
         */
        LogLine: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Level
             * @default INFO
             * @enum {string}
             */
            level: "DEBUG" | "INFO" | "WARNING" | "ERROR" | "CRITICAL";
            /**
             * Stream
             * @enum {string}
             */
            stream: "stdout" | "stderr";
            /** Text */
            text: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * MeView
         * @description Current principal. ``id``/``username`` are ``None`` in local mode
         *     (auth disabled — the synthetic superadmin has no user row).
         */
        MeView: {
            /** Id */
            id: number | null;
            /** Superadmin */
            superadmin: boolean;
            /** Tenants */
            tenants: components["schemas"]["TenantRoleView"][];
            /** Username */
            username: string | null;
        };
        /** MemberView */
        MemberView: {
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "viewer";
            /** User Id */
            user_id: number;
            /** Username */
            username: string;
        };
        /**
         * ObjectDeleted
         * @description Response from ``internal_api.delete_object`` — name of the dropped table.
         */
        ObjectDeleted: {
            /** Name */
            name: string;
        };
        /**
         * ObjectDetail
         * @description Full object representation used by ``GET /objects/{name}``.
         */
        ObjectDetail: {
            /** Created At */
            created_at?: string | null;
            /** Lineage Summary */
            lineage_summary?: string | null;
            /** Name */
            name: string;
            /** Persistent */
            persistent: boolean;
            /** Row Count */
            row_count?: number | null;
            /**
             * Scope
             * @enum {string}
             */
            scope: "temp" | "temp_named" | "job" | "global";
            /** Size Bytes */
            size_bytes?: number | null;
            /** Table */
            table: string;
            table_schema: components["schemas"]["Schema"];
        };
        /**
         * ObjectView
         * @description Compact object representation used by list endpoints.
         */
        ObjectView: {
            /** Created At */
            created_at?: string | null;
            /** Name */
            name: string;
            /** Persistent */
            persistent: boolean;
            /** Row Count */
            row_count?: number | null;
            /**
             * Scope
             * @enum {string}
             */
            scope: "temp" | "temp_named" | "job" | "global";
            /** Size Bytes */
            size_bytes?: number | null;
            /** Table */
            table: string;
        };
        /** Page[ExecutionWorkerView] */
        Page_ExecutionWorkerView_: {
            /** Items */
            items: components["schemas"]["ExecutionWorkerView"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total?: number | null;
        };
        /** Page[JobView] */
        Page_JobView_: {
            /** Items */
            items: components["schemas"]["JobView"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total?: number | null;
        };
        /** Page[MemberView] */
        Page_MemberView_: {
            /** Items */
            items: components["schemas"]["MemberView"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total?: number | null;
        };
        /** Page[ObjectView] */
        Page_ObjectView_: {
            /** Items */
            items: components["schemas"]["ObjectView"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total?: number | null;
        };
        /** Page[RegisteredJobView] */
        Page_RegisteredJobView_: {
            /** Items */
            items: components["schemas"]["RegisteredJobView"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total?: number | null;
        };
        /** Page[TenantView] */
        Page_TenantView_: {
            /** Items */
            items: components["schemas"]["TenantView"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total?: number | null;
        };
        /** Page[UserView] */
        Page_UserView_: {
            /** Items */
            items: components["schemas"]["UserView"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total?: number | null;
        };
        /**
         * Problem
         * @description RFC 7807-style error payload used by the REST surface.
         */
        Problem: {
            code?: components["schemas"]["ProblemCode"] | null;
            /** Detail */
            detail?: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
        };
        /**
         * ProblemCode
         * @description Stable machine-readable code attached to every ``Problem`` response.
         * @enum {string}
         */
        ProblemCode: "not_found" | "conflict" | "invalid" | "unauthorized" | "forbidden" | "execution_worker_spawn_failed";
        /**
         * PurgeObjectsRequest
         * @description Inputs for ``internal_api.purge_objects``.
         *
         *     At least one of ``after`` / ``before`` must be set — the internal_api
         *     refuses to purge everything unfiltered.
         */
        PurgeObjectsRequest: {
            /** After */
            after?: string | null;
            /** Before */
            before?: string | null;
        };
        /**
         * PurgeObjectsResult
         * @description Response from ``internal_api.purge_objects`` — names of dropped tables.
         */
        PurgeObjectsResult: {
            /** Deleted */
            deleted: string[];
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RegisterJobRequest
         * @description Inputs for ``internal_api.register_job``.
         *
         *     ``name`` defaults to the last dotted segment of ``entrypoint`` (pass ``""``
         *     or omit to opt in), so every surface — CLI, REST, MCP — gets the same
         *     shorthand without redoing the derivation at the call site.
         */
        RegisterJobRequest: {
            /** Default Kwargs */
            default_kwargs?: {
                [key: string]: unknown;
            } | null;
            /** Dockerfile */
            dockerfile?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Entrypoint */
            entrypoint: string;
            /** Git Remote */
            git_remote?: string | null;
            /** Image */
            image?: string | null;
            /** Kubernetes Config */
            kubernetes_config?: {
                [key: string]: unknown;
            } | null;
            /**
             * Name
             * @default
             */
            name: string;
            /** Preservation Mode */
            preservation_mode?: ("NONE" | "FULL") | null;
            /**
             * Runner Mode
             * @default subprocess
             * @enum {string}
             */
            runner_mode: "subprocess" | "docker" | "kubernetes";
            /** Schedule */
            schedule?: string | null;
        };
        /**
         * RegisteredJobView
         * @description Registered job representation used by ``GET /registered-jobs``.
         */
        RegisteredJobView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Default Kwargs */
            default_kwargs?: {
                [key: string]: unknown;
            } | null;
            /** Enabled */
            enabled: boolean;
            /** Entrypoint */
            entrypoint: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Next Run At */
            next_run_at?: string | null;
            /** Preservation Mode */
            preservation_mode?: ("NONE" | "FULL") | null;
            /** Schedule */
            schedule?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RunJobRequest
         * @description Inputs for ``internal_api.run_job``.
         */
        RunJobRequest: {
            /** Command */
            command?: string[] | null;
            /** Command Env */
            command_env?: {
                [key: string]: string;
            } | null;
            /** Dockerfile */
            dockerfile?: string | null;
            /**
             * Entry Type
             * @default module
             * @enum {string}
             */
            entry_type: "module" | "shell";
            /** Git Branch */
            git_branch?: string | null;
            /** Git Remote */
            git_remote?: string | null;
            /** Git Sha */
            git_sha?: string | null;
            /** Image */
            image?: string | null;
            /** Image Pull Secret */
            image_pull_secret?: string | null;
            /** Kwargs */
            kwargs?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Namespace */
            namespace?: string | null;
            /** Preservation Mode */
            preservation_mode?: ("NONE" | "FULL") | null;
            /** Service Account */
            service_account?: string | null;
        };
        /**
         * Schema
         * @description Schema definition for Object tables. Also serves as Object metadata
         *     when table is set.
         *
         *     Attributes:
         *         fieldtype: Overall fieldtype - 's' for scalar, 'a' for array, 'd' for dict
         *         columns: Dict mapping column names to ColumnInfo. Each ColumnInfo carries
         *                  its own per-column fieldtype, replacing the legacy
         *                  ``col_fieldtype`` / YAML-COMMENT mechanism.
         *         table: ClickHouse table name (empty for blueprints, set for realized objects)
         *         engine: ClickHouse table engine. If None, uses context's engine setting.
         *         order_by: ORDER BY key for MergeTree-family engines. If None, defaults to tuple().
         */
        Schema: {
            /** Columns */
            columns: {
                [key: string]: components["schemas"]["ColumnInfo"];
            };
            /** Engine */
            engine?: ("MergeTree" | "AggregatingMergeTree" | "Memory") | null;
            /** Fieldtype */
            fieldtype: string;
            /** Order By */
            order_by?: string | null;
            /** Table */
            table?: string | null;
        };
        /** SetMemberRequest */
        SetMemberRequest: {
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "viewer";
        };
        /** SetPasswordRequest */
        SetPasswordRequest: {
            /** Password */
            password: string;
        };
        /** SetSuperadminRequest */
        SetSuperadminRequest: {
            /** Superadmin */
            superadmin: boolean;
        };
        /**
         * StartExecutionWorkerRequest
         * @description Inputs for ``internal_api.start_execution_worker``.
         *
         *     ``max_tasks`` caps how many tasks the spawned execution worker executes
         *     before it exits; ``None`` means unlimited (run until stopped).
         */
        StartExecutionWorkerRequest: {
            /** Max Tasks */
            max_tasks?: number | null;
        };
        /**
         * TaskDetail
         * @description Full task representation used by ``GET /tasks/{id}``.
         */
        TaskDetail: {
            /** Attempt */
            attempt: number;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entrypoint */
            entrypoint: string;
            /** Error */
            error?: string | null;
            /** Execution Worker Id */
            execution_worker_id?: string | null;
            /** Id */
            id: string;
            /**
             * Is Image Build
             * @default false
             */
            is_image_build: boolean;
            /** Job Id */
            job_id: string;
            /** Kwargs */
            kwargs?: {
                [key: string]: unknown;
            };
            /**
             * Max Retries
             * @default 0
             */
            max_retries: number;
            /** Name */
            name: string;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "CLAIMED" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "PENDING_CLEANUP" | "UPSTREAM_FAILED";
        };
        /**
         * TaskLogsView
         * @description Captured log lines for a task, served by ``GET /tasks/{id}/logs``.
         */
        TaskLogsView: {
            /** Available */
            available: boolean;
            /** Lines */
            lines?: components["schemas"]["LogLine"][];
        };
        /**
         * TaskStatsView
         * @description Per-task execution stats exposed inside ``JobStatsView``.
         */
        TaskStatsView: {
            /** Entrypoint */
            entrypoint: string;
            /** Error */
            error?: string | null;
            /** Exec Time Ms */
            exec_time_ms?: number | null;
            /** Id */
            id: string;
            /** Queue Time Ms */
            queue_time_ms?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "CLAIMED" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "PENDING_CLEANUP" | "UPSTREAM_FAILED";
        };
        /**
         * TaskView
         * @description Compact task representation used by list endpoints and ``JobDetail``.
         */
        TaskView: {
            /** Attempt */
            attempt: number;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entrypoint */
            entrypoint: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /**
             * Is Image Build
             * @default false
             */
            is_image_build: boolean;
            /** Job Id */
            job_id: string;
            /** Name */
            name: string;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "CLAIMED" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "PENDING_CLEANUP" | "UPSTREAM_FAILED";
        };
        /** TenantRoleView */
        TenantRoleView: {
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "viewer";
            /** Slug */
            slug: string;
            /** Tenant Id */
            tenant_id: string;
        };
        /** TenantView */
        TenantView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserView */
        UserView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Disabled */
            disabled: boolean;
            /** Id */
            id: number;
            /** Superadmin */
            superadmin: boolean;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v0_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v0_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v0_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeView"];
                };
            };
        };
    };
    change_password_api_v0_auth_me_password_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid Request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    refresh_api_v0_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_v0_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_execution_workers_api_v0_execution_workers_get: {
        parameters: {
            query?: {
                status?: ("ACTIVE" | "IDLE" | "STOPPING" | "STOPPED") | null;
                limit?: number;
                offset?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ExecutionWorkerView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_execution_worker_api_v0_execution_workers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartExecutionWorkerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid Request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description ExecutionWorker Spawn Failed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    stop_execution_worker_api_v0_execution_workers__execution_worker_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_worker_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionWorkerView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v0_jobs_get: {
        parameters: {
            query?: {
                status?: ("PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED") | null;
                name?: string | null;
                since?: string | null;
                limit?: number;
                offset?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_JobView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v0_jobs__ref__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v0_jobs__ref__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_graph_api_v0_jobs__ref__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobGraphView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_stats_api_v0_jobs__ref__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatsView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_job_api_v0_jobs_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_objects_api_v0_objects_get: {
        parameters: {
            query?: {
                prefix?: string | null;
                scope?: ("temp" | "temp_named" | "job" | "global") | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ObjectView_"];
                };
            };
            /** @description Invalid Request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_object_api_v0_objects__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_object_api_v0_objects__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectDeleted"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_objects_api_v0_objects_purge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurgeObjectsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurgeObjectsResult"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid Request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_registered_jobs_api_v0_registered_jobs_get: {
        parameters: {
            query?: {
                enabled?: boolean | null;
                name?: string | null;
                limit?: number;
                offset?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RegisteredJobView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_job_api_v0_registered_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredJobView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid Request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    disable_job_api_v0_registered_jobs__name__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredJobView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_job_api_v0_registered_jobs__name__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredJobView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v0_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_task_api_v0_tasks__task_id__clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearTaskView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_logs_api_v0_tasks__task_id__logs_get: {
        parameters: {
            query?: {
                /** @description Return only the last N log lines. */
                tail?: number | null;
            };
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskLogsView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tenants_api_v0_tenants_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TenantView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tenant_api_v0_tenants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantView"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tenant_api_v0_tenants__tenant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_v0_tenants__tenant_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MemberView_"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_member_api_v0_tenants__tenant_id__members__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: number;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_v0_tenants__tenant_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: number;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v0_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v0_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_user_api_v0_users__user_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_password_api_v0_users__user_id__password_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_superadmin_api_v0_users__user_id__superadmin_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSuperadminRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
