/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v0/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v0_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v0_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v0_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v0_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v0_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/jobs/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v0_jobs__ref__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/jobs/{ref}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v0_jobs__ref__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/jobs/{ref}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Stats */
        get: operations["job_stats_api_v0_jobs__ref__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/jobs:run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Job */
        post: operations["run_job_api_v0_jobs_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Objects */
        get: operations["list_objects_api_v0_objects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/objects/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Object */
        get: operations["get_object_api_v0_objects__name__get"];
        put?: never;
        post?: never;
        /** Delete Object */
        delete: operations["delete_object_api_v0_objects__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/objects:purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Purge Objects */
        post: operations["purge_objects_api_v0_objects_purge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/registered-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Registered Jobs */
        get: operations["list_registered_jobs_api_v0_registered_jobs_get"];
        put?: never;
        /** Register Job */
        post: operations["register_job_api_v0_registered_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/registered-jobs/{name}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Job */
        post: operations["disable_job_api_v0_registered_jobs__name__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/registered-jobs/{name}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable Job */
        post: operations["enable_job_api_v0_registered_jobs__name__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v0_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/tasks/{task_id}/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Task */
        post: operations["clear_task_api_v0_tasks__task_id__clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/tasks/{task_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Logs */
        get: operations["get_task_logs_api_v0_tasks__task_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v0_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v0_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/users/{user_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable User */
        post: operations["disable_user_api_v0_users__user_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/users/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Password */
        put: operations["set_password_api_v0_users__user_id__password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Role */
        put: operations["set_role_api_v0_users__user_id__role_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workers */
        get: operations["list_workers_api_v0_workers_get"];
        put?: never;
        /**
         * Start Worker
         * @description Spawn a detached worker subprocess (distributed mode only).
         *
         *     Returns ``202 Accepted`` with an empty body once the fork/exec succeeds;
         *     the caller polls ``GET /workers`` to observe the new worker row.
         */
        post: operations["start_worker_api_v0_workers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/workers/{worker_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Worker */
        post: operations["stop_worker_api_v0_workers__worker_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ClearTaskView
         * @description Result of ``POST /tasks/{id}/clear`` — the reactivated job plus the
         *     full set of tasks that were reset to ``PENDING`` (target + downstream).
         */
        ClearTaskView: {
            /** Cleared Task Ids */
            cleared_task_ids?: number[];
            job: components["schemas"]["JobView"];
        };
        /**
         * ColumnInfo
         * @description Column definition including base type, nullability, array wrapping, and cardinality.
         *
         *     Attributes:
         *         type: Base ClickHouse element type (e.g., 'Int64', 'String')
         *         nullable: Whether the column allows NULL values
         *         array: Nesting depth of Array wrapping. ``0`` means plain column,
         *                ``1`` means ``Array(T)``, ``2`` means ``Array(Array(T))``, etc.
         *                Bool ``True``/``False`` are accepted as ``1``/``0`` for convenience.
         *         low_cardinality: Whether to use LowCardinality encoding
         *         fieldtype: Per-column fieldtype — scalar or array. Replaces the YAML-comment
         *                    fieldtype stored in ClickHouse today; populated from the registry's
         *                    schema_doc once Phase 3 writes it.
         */
        ColumnInfo: {
            /**
             * Array
             * @default 0
             */
            array: number;
            /** Default */
            default?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Fieldtype
             * @default s
             * @enum {string}
             */
            fieldtype: "s" | "a";
            /**
             * Low Cardinality
             * @default false
             */
            low_cardinality: boolean;
            /**
             * Nullable
             * @default false
             */
            nullable: boolean;
            /** Type */
            type: string;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /** Password */
            password: string;
            /**
             * Role
             * @default viewer
             * @enum {string}
             */
            role: "admin" | "viewer";
            /** Username */
            username: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobDetail
         * @description Full job representation used by ``GET /jobs/{ref}``.
         */
        JobDetail: {
            /** Completed At */
            completed_at?: string | null;
            /**
             * Completed Tasks
             * @default 0
             */
            completed_tasks: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error */
            error?: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Preservation Mode
             * @enum {string}
             */
            preservation_mode: "NONE" | "FULL";
            /** Registered Job Id */
            registered_job_id?: number | null;
            /**
             * Run Type
             * @enum {string}
             */
            run_type: "SCHEDULED" | "MANUAL";
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED";
            /** Tasks */
            tasks?: components["schemas"]["TaskView"][];
            /**
             * Total Tasks
             * @default 0
             */
            total_tasks: number;
        };
        /**
         * JobStatsView
         * @description Execution stats for a job and all its tasks.
         *
         *     Replacement for ``aaiclick.orchestration.jobs.stats.JobStats`` — Phase 2
         *     migrates callers, after which the old dataclass is removed.
         */
        JobStatsView: {
            /** Exec Time Ms */
            exec_time_ms?: number | null;
            /** Job Id */
            job_id: number;
            /** Job Name */
            job_name: string;
            /**
             * Job Status
             * @enum {string}
             */
            job_status: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED";
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Tasks */
            tasks?: components["schemas"]["TaskStatsView"][];
            /** Total Tasks */
            total_tasks: number;
            /** Wall Time Ms */
            wall_time_ms?: number | null;
        };
        /**
         * JobView
         * @description Compact job representation used by list endpoints.
         */
        JobView: {
            /** Completed At */
            completed_at?: string | null;
            /**
             * Completed Tasks
             * @default 0
             */
            completed_tasks: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Preservation Mode
             * @enum {string}
             */
            preservation_mode: "NONE" | "FULL";
            /** Registered Job Id */
            registered_job_id?: number | null;
            /**
             * Run Type
             * @enum {string}
             */
            run_type: "SCHEDULED" | "MANUAL";
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED";
            /**
             * Total Tasks
             * @default 0
             */
            total_tasks: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** MeView */
        MeView: {
            /** Id */
            id: number;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "viewer";
            /** Username */
            username: string;
        };
        /**
         * ObjectDeleted
         * @description Response from ``internal_api.delete_object`` — name of the dropped table.
         */
        ObjectDeleted: {
            /** Name */
            name: string;
        };
        /**
         * ObjectDetail
         * @description Full object representation used by ``GET /objects/{name}``.
         */
        ObjectDetail: {
            /** Created At */
            created_at?: string | null;
            /** Lineage Summary */
            lineage_summary?: string | null;
            /** Name */
            name: string;
            /** Persistent */
            persistent: boolean;
            /** Row Count */
            row_count?: number | null;
            /**
             * Scope
             * @enum {string}
             */
            scope: "temp" | "temp_named" | "job" | "global";
            /** Size Bytes */
            size_bytes?: number | null;
            /** Table */
            table: string;
            table_schema: components["schemas"]["Schema"];
        };
        /**
         * ObjectView
         * @description Compact object representation used by list endpoints.
         */
        ObjectView: {
            /** Created At */
            created_at?: string | null;
            /** Name */
            name: string;
            /** Persistent */
            persistent: boolean;
            /** Row Count */
            row_count?: number | null;
            /**
             * Scope
             * @enum {string}
             */
            scope: "temp" | "temp_named" | "job" | "global";
            /** Size Bytes */
            size_bytes?: number | null;
            /** Table */
            table: string;
        };
        /** Page[JobView] */
        Page_JobView_: {
            /** Items */
            items: components["schemas"]["JobView"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total?: number | null;
        };
        /** Page[ObjectView] */
        Page_ObjectView_: {
            /** Items */
            items: components["schemas"]["ObjectView"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total?: number | null;
        };
        /** Page[RegisteredJobView] */
        Page_RegisteredJobView_: {
            /** Items */
            items: components["schemas"]["RegisteredJobView"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total?: number | null;
        };
        /** Page[UserView] */
        Page_UserView_: {
            /** Items */
            items: components["schemas"]["UserView"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total?: number | null;
        };
        /** Page[WorkerView] */
        Page_WorkerView_: {
            /** Items */
            items: components["schemas"]["WorkerView"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total?: number | null;
        };
        /**
         * Problem
         * @description RFC 7807-style error payload used by the REST surface.
         */
        Problem: {
            code?: components["schemas"]["ProblemCode"] | null;
            /** Detail */
            detail?: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
        };
        /**
         * ProblemCode
         * @description Stable machine-readable code attached to every ``Problem`` response.
         * @enum {string}
         */
        ProblemCode: "not_found" | "conflict" | "invalid" | "unauthorized" | "forbidden" | "worker_spawn_failed";
        /**
         * PurgeObjectsRequest
         * @description Inputs for ``internal_api.purge_objects``.
         *
         *     At least one of ``after`` / ``before`` must be set — the internal_api
         *     refuses to purge everything unfiltered.
         */
        PurgeObjectsRequest: {
            /** After */
            after?: string | null;
            /** Before */
            before?: string | null;
        };
        /**
         * PurgeObjectsResult
         * @description Response from ``internal_api.purge_objects`` — names of dropped tables.
         */
        PurgeObjectsResult: {
            /** Deleted */
            deleted: string[];
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RegisterJobRequest
         * @description Inputs for ``internal_api.register_job``.
         *
         *     ``name`` defaults to the last dotted segment of ``entrypoint`` (pass ``""``
         *     or omit to opt in), so every surface — CLI, REST, MCP — gets the same
         *     shorthand without redoing the derivation at the call site.
         */
        RegisterJobRequest: {
            /** Default Kwargs */
            default_kwargs?: {
                [key: string]: unknown;
            } | null;
            /** Dockerfile */
            dockerfile?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Entrypoint */
            entrypoint: string;
            /** Git Remote */
            git_remote?: string | null;
            /** Kubernetes Config */
            kubernetes_config?: {
                [key: string]: unknown;
            } | null;
            /**
             * Name
             * @default
             */
            name: string;
            /** Preservation Mode */
            preservation_mode?: ("NONE" | "FULL") | null;
            /**
             * Runner Mode
             * @default subprocess
             * @enum {string}
             */
            runner_mode: "subprocess" | "docker" | "kubernetes";
            /** Schedule */
            schedule?: string | null;
        };
        /**
         * RegisteredJobView
         * @description Registered job representation used by ``GET /registered-jobs``.
         */
        RegisteredJobView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Default Kwargs */
            default_kwargs?: {
                [key: string]: unknown;
            } | null;
            /** Enabled */
            enabled: boolean;
            /** Entrypoint */
            entrypoint: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Next Run At */
            next_run_at?: string | null;
            /** Preservation Mode */
            preservation_mode?: ("NONE" | "FULL") | null;
            /** Schedule */
            schedule?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RunJobRequest
         * @description Inputs for ``internal_api.run_job``.
         */
        RunJobRequest: {
            /** Dockerfile */
            dockerfile?: string | null;
            /** Git Branch */
            git_branch?: string | null;
            /** Git Remote */
            git_remote?: string | null;
            /** Git Sha */
            git_sha?: string | null;
            /** Image Pull Secret */
            image_pull_secret?: string | null;
            /** Kwargs */
            kwargs?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Namespace */
            namespace?: string | null;
            /** Preservation Mode */
            preservation_mode?: ("NONE" | "FULL") | null;
            /** Service Account */
            service_account?: string | null;
        };
        /**
         * Schema
         * @description Schema definition for Object tables. Also serves as Object metadata
         *     when table is set.
         *
         *     Attributes:
         *         fieldtype: Overall fieldtype - 's' for scalar, 'a' for array, 'd' for dict
         *         columns: Dict mapping column names to ColumnInfo. Each ColumnInfo carries
         *                  its own per-column fieldtype, replacing the legacy
         *                  ``col_fieldtype`` / YAML-COMMENT mechanism.
         *         table: ClickHouse table name (empty for blueprints, set for realized objects)
         *         engine: ClickHouse table engine. If None, uses context's engine setting.
         *         order_by: ORDER BY key for MergeTree-family engines. If None, defaults to tuple().
         */
        Schema: {
            /** Columns */
            columns: {
                [key: string]: components["schemas"]["ColumnInfo"];
            };
            /** Engine */
            engine?: ("MergeTree" | "AggregatingMergeTree" | "Memory") | null;
            /** Fieldtype */
            fieldtype: string;
            /** Order By */
            order_by?: string | null;
            /** Table */
            table?: string | null;
        };
        /** SetPasswordRequest */
        SetPasswordRequest: {
            /** Password */
            password: string;
        };
        /** SetRoleRequest */
        SetRoleRequest: {
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "viewer";
        };
        /**
         * StartWorkerRequest
         * @description Inputs for ``internal_api.start_worker``.
         *
         *     ``max_tasks`` caps how many tasks the spawned worker executes before it
         *     exits; ``None`` means unlimited (run until stopped).
         */
        StartWorkerRequest: {
            /** Max Tasks */
            max_tasks?: number | null;
        };
        /**
         * TaskDetail
         * @description Full task representation used by ``GET /tasks/{id}``.
         */
        TaskDetail: {
            /** Attempt */
            attempt: number;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entrypoint */
            entrypoint: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: number;
            /** Job Id */
            job_id: number;
            /** Kwargs */
            kwargs?: {
                [key: string]: unknown;
            };
            /** Log Path */
            log_path?: string | null;
            /**
             * Max Retries
             * @default 0
             */
            max_retries: number;
            /** Name */
            name: string;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "CLAIMED" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "PENDING_CLEANUP" | "UPSTREAM_FAILED";
            /** Worker Id */
            worker_id?: number | null;
        };
        /**
         * TaskLogsView
         * @description Captured log lines for a task, served by ``GET /tasks/{id}/logs``.
         */
        TaskLogsView: {
            /** Available */
            available: boolean;
            /** Lines */
            lines?: string[];
            /** Log Path */
            log_path?: string | null;
        };
        /**
         * TaskStatsView
         * @description Per-task execution stats exposed inside ``JobStatsView``.
         */
        TaskStatsView: {
            /** Entrypoint */
            entrypoint: string;
            /** Error */
            error?: string | null;
            /** Exec Time Ms */
            exec_time_ms?: number | null;
            /** Id */
            id: number;
            /** Queue Time Ms */
            queue_time_ms?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "CLAIMED" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "PENDING_CLEANUP" | "UPSTREAM_FAILED";
        };
        /**
         * TaskView
         * @description Compact task representation used by list endpoints and ``JobDetail``.
         */
        TaskView: {
            /** Attempt */
            attempt: number;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entrypoint */
            entrypoint: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: number;
            /** Job Id */
            job_id: number;
            /** Name */
            name: string;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "CLAIMED" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "PENDING_CLEANUP" | "UPSTREAM_FAILED";
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserView */
        UserView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Disabled */
            disabled: boolean;
            /** Id */
            id: number;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "viewer";
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkerView
         * @description Worker representation used by ``GET /workers``.
         */
        WorkerView: {
            /** Hostname */
            hostname: string;
            /** Id */
            id: number;
            /**
             * Last Heartbeat
             * Format: date-time
             */
            last_heartbeat: string;
            /** Pid */
            pid: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ACTIVE" | "IDLE" | "STOPPING" | "STOPPED";
            /** Tasks Completed */
            tasks_completed: number;
            /** Tasks Failed */
            tasks_failed: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v0_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v0_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v0_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeView"];
                };
            };
        };
    };
    refresh_api_v0_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v0_jobs_get: {
        parameters: {
            query?: {
                status?: ("PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED") | null;
                name?: string | null;
                since?: string | null;
                limit?: number;
                offset?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_JobView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v0_jobs__ref__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v0_jobs__ref__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_stats_api_v0_jobs__ref__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: number | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatsView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_job_api_v0_jobs_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_objects_api_v0_objects_get: {
        parameters: {
            query?: {
                prefix?: string | null;
                scope?: ("temp" | "temp_named" | "job" | "global") | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ObjectView_"];
                };
            };
            /** @description Invalid Request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_object_api_v0_objects__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_object_api_v0_objects__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectDeleted"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_objects_api_v0_objects_purge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurgeObjectsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurgeObjectsResult"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid Request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_registered_jobs_api_v0_registered_jobs_get: {
        parameters: {
            query?: {
                enabled?: boolean | null;
                name?: string | null;
                limit?: number;
                offset?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RegisteredJobView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_job_api_v0_registered_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredJobView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid Request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    disable_job_api_v0_registered_jobs__name__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredJobView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_job_api_v0_registered_jobs__name__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredJobView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v0_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_task_api_v0_tasks__task_id__clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearTaskView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_logs_api_v0_tasks__task_id__logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskLogsView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v0_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v0_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_user_api_v0_users__user_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_password_api_v0_users__user_id__password_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_role_api_v0_users__user_id__role_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workers_api_v0_workers_get: {
        parameters: {
            query?: {
                status?: ("ACTIVE" | "IDLE" | "STOPPING" | "STOPPED") | null;
                limit?: number;
                offset?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_WorkerView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_worker_api_v0_workers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartWorkerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid Request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Worker Spawn Failed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    stop_worker_api_v0_workers__worker_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worker_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
