name: run-all-projects

on:
  schedule:
    - cron: '0 0 * * *'  # Nightly at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  basic-worker:
    uses: ./.github/workflows/project-example.yaml
    with:
      project: basic_worker

  nyc-taxi-pipeline:
    uses: ./.github/workflows/project-example.yaml
    with:
      project: nyc_taxi_pipeline

  cyber-threat-feeds:
    uses: ./.github/workflows/project-example.yaml
    with:
      project: cyber_threat_feeds

  basic-lineage:
    uses: ./.github/workflows/project-basic-lineage.yaml
    with:
      ai_preset: nim
