name: run-all-projects

on:
  schedule:
    - cron: '0 0 * * *'  # Nightly at 00:00 UTC
  workflow_dispatch:

jobs:
  basic-worker:
    uses: ./.github/workflows/project-basic-worker.yaml
    permissions:
      contents: read
      actions: read
      checks: write

  nyc-taxi-pipeline:
    uses: ./.github/workflows/project-nyc-taxi-pipeline.yaml
    permissions:
      contents: read
      actions: read
      checks: write

  cyber-threat-feeds:
    uses: ./.github/workflows/project-cyber-threat-feeds.yaml
    permissions:
      contents: read
      actions: read
      checks: write

  imdb-dataset-builder:
    uses: ./.github/workflows/project-imdb-dataset-builder.yaml
    permissions:
      contents: read
      actions: read
      checks: write

  basic-lineage:
    uses: ./.github/workflows/project-basic-lineage.yaml
    permissions:
      contents: read
      actions: read
      checks: write

  ai-tests:
    uses: ./.github/workflows/project-ai-tests.yaml
    permissions:
      contents: read
      actions: read
      checks: write
